---
repos:
  - hooks:
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.13.2